project:
  type: website
  output-dir: _site

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true

website:
  title: "My Portfolio"
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: "Projects"
        href: project.html
      - text: "Resume"
        href: resume.html
      - text: "Contact"
        href: contact.html
